In [1]:
import   numpy as np
import pandas as pd

Section A - Easy (15 Questions)
1. Create a DataFrame named student_df from a dictionary containing the columns Name, Age, and City for
four students.

In [2]:
dic = {
    'name' :['manish','rohit','sunita','aman'],
    'age' : [20,26,15,25],
    'city': ['mathura','agra','raya','hathras']
}

student_df = pd.DataFrame(dic)

     name  age     city
0  manish   20  mathura
1   rohit   26     agra
2  sunita   15     raya
3    aman   25  hathras

2. Display the complete student_df DataFrame.

In [3]:
student_df

     name  age     city
0  manish   20  mathura
1   rohit   26     agra
2  sunita   15     raya
3    aman   25  hathras

3. Write code to display the column names of student_df.
```
# This is formatted as code
```

In [4]:
student_df.columns

Index(['name', 'age', 'city'], dtype='object')

4. Retrieve the Name column from student_df.

In [5]:
student_df['name']

0    manish
1     rohit
2    sunita
3      aman
Name: name, dtype: object

5. Retrieve the City column from student_df using square-bracket notation.

In [6]:
student_df['city']

0    mathura
1       agra
2       raya
3    hathras
Name: city, dtype: object

6. Create a new DataFrame from student_df containing only the columns Name and City.

In [7]:
new_df = student_df[['name','city']]
new_df

     name     city
0  manish  mathura
1   rohit     agra
2  sunita     raya
3    aman  hathras

7. Create a DataFrame named book_df from a dictionary of equal-length lists containing Book, Author, and
Price.

In [8]:
df = {
    'book': ['Ramayan', 'Bhagavad Geeta', 'Ramcharitmanas'],
    'author': ['Valmiki', 'Ved Vyasa', 'Tulsidas'],
    'price': [350, 250, 400]
}

book_df = pd.DataFrame(df)
book_df

             book     author  price
0         Ramayan    Valmiki    350
1  Bhagavad Geeta  Ved Vyasa    250
2  Ramcharitmanas   Tulsidas    400

8. Add a new column named Publisher to book_df and assign the same publisher name to every row.

In [10]:
book_df['discount']    = 10
book_df

# too addd new column in dataframe we can use square bracket

             book     author  price publisher  discount
0         Ramayan    Valmiki    350   krishna        10
1  Bhagavad Geeta  Ved Vyasa    250   krishna        10
2  Ramcharitmanas   Tulsidas    400   krishna        10

9. Create a five-row DataFrame and assign the values generated by np.arange(5) to a new column named
SerialNo.

In [14]:
df = pd.DataFrame(np.arange(5),columns = ['serial_no'])
df

   serial_no
0          0
1          1
2          2
3          3
4          4

10. Delete the SerialNo column from the DataFrame created in Question 9.

In [17]:
del df['serial_no']
df

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

11. Create a DataFrame named movie_df containing the columns Movie, Year, and Rating.

In [24]:
dic = {
    'movie' :['dhoom 3','sikandar','sultan'],
    'year'  : [2008,2009,2010],
    'rating' : [4,3,5]
}
movie_df = pd.DataFrame(dic)
movie_df

      movie  year  rating
0   dhoom 3  2008       4
1  sikandar  2009       3
2    sultan  2010       5

12. From movie_df, create another DataFrame containing the columns Movie, Rating, and a new requested
column named Director that is not present in the original DataFrame.

In [27]:
df = pd.DataFrame(movie_df,columns =['movie','rating','year','director'])
df

      movie  rating  year  director
0   dhoom 3       4  2008       NaN
1  sikandar       3  2009       NaN
2    sultan       5  2010       NaN

13. Create a Series containing two city names at indexes 0 and 3.

In [30]:
ser  = pd.Series(['mathura','agra'],index = [0,3])
ser

0    mathura
3       agra
dtype: object

14. Assign the Series from Question 13 to a new column named Branch in a four-row DataFrame.

In [35]:
df = pd.DataFrame(np.arange(4),columns = ['branch'])
df['branch'] = ser
df

    branch
0  mathura
1      NaN
2      NaN
3     agra

16. Create a five-row DataFrame named employee_df with columns Employee, Department, and
Experience. Display only Employee and Experience in a new DataFrame.

In [36]:


employee_df = pd.DataFrame({
    'Employee': ['Aman', 'Riya', 'Rahul', 'Priya', 'Karan'],
    'Department': ['IT', 'HR', 'Sales', 'IT', 'Finance'],
    'Experience': [2, 4, 3, 5, 1]
})

new_df = employee_df[['Employee', 'Experience']]

print(new_df)

  Employee  Experience
0     Aman           2
1     Riya           4
2    Rahul           3
3    Priya           5
4    Karan           1

17. Using employee_df, retrieve the Department column using one-column access and then display all
column names.

In [40]:
print(employee_df['Department'])
print(" ")
print(employee_df.columns)

0         IT
1         HR
2      Sales
3         IT
4    Finance
Name: Department, dtype: object

Index(['Employee', 'Department', 'Experience'], dtype='object')

18. Add a new column named Office to employee_df and assign 'Head Office' to every row. Then display the
updated DataFrame.

In [41]:
employee_df['office'] = 'head office'
employee_df

  Employee Department  Experience       office
0     Aman         IT           2  head office
1     Riya         HR           4  head office
2    Rahul      Sales           3  head office
3    Priya         IT           5  head office
4    Karan    Finance           1  head office

19. Replace the values in the Office column with numbers generated using np.arange(5).

In [43]:
employee_df['office'] = np.arange(5)
employee_df

  Employee Department  Experience  office
0     Aman         IT           2       0
1     Riya         HR           4       1
2    Rahul      Sales           3       2
3    Priya         IT           5       3
4    Karan    Finance           1       4

20. Create a Series named office_names containing 'Delhi', 'Mumbai', and 'Pune' at indexes 0, 2, and 4.
Assign it to the Office column of employee_df and display the result.

In [44]:
office_name = pd.Series(['Delhi','mumbai','pune'],index = [0,2,4])
employee_df['office'] = office_name
employee_df

  Employee Department  Experience  office
0     Aman         IT           2   Delhi
1     Riya         HR           4     NaN
2    Rahul      Sales           3  mumbai
3    Priya         IT           5     NaN
4    Karan    Finance           1    pune

21. Delete the Office column from employee_df and display the remaining columns.

In [51]:
del employee_df['office']
employee_df

KeyError: 'office'

22. Create a DataFrame named product_df from a dictionary containing Product, Category, and Price. Then
construct another DataFrame with the columns ordered as Price, Product, Category.

In [52]:
product_df = pd.DataFrame({
    'Product': ['Laptop', 'Phone', 'Tablet'],
    'Category': ['Electronics', 'Electronics', 'Electronics'],
    'Price': [1000, 500, 300]
})

23. Construct a DataFrame from existing data while requesting four columns, where one of the requested
columns does not exist in the source data. Display the resulting DataFrame and inspect what appears in the
missing column.

In [54]:
data = {
    'Name': ['Aman', 'Riya', 'Rahul'],
    'Age': [20, 21, 19],
    'Marks': [85, 90, 78]
}

df = pd.DataFrame(
    data,
    columns=['Name', 'Age', 'Marks', 'City']
)

df

    Name  Age  Marks City
0   Aman   20     85  NaN
1   Riya   21     90  NaN
2  Rahul   19     78  NaN

Create a DataFrame with a column name containing a space, such as Total Marks. Retrieve that column
using the appropriate column-selection syntax demonstrated in the notebook.

In [55]:
df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Rahul'],
    'Age': [20, 21, 19],
    'Total Marks': [85, 90, 78]
})

df

    Name  Age  Total Marks
0   Aman   20           85
1   Riya   21           90
2  Rahul   19           78

25. Read a copied table into a DataFrame using pd.read_clipboard(). Display its column names and then
create a second DataFrame containing any three selected columns.

In [56]:
df = pd.read_clipboard()

print(df.columns)

PyperclipException:
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit
    https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error