In [48]:
import numpy as np
import pandas as pd

NumPy 1. Create a NumPy array containing odd integers from 11 to 29. Display its number of dimensions and total number of elements.

In [17]:
arr = np.arange(11,30,2)
print(arr)
print(arr.ndim)
print(arr.size)

[11 13 15 17 19 21 23 25 27 29]
1
10

2. Use NumPy to generate seven equally spaced values between 5 and 35, including both endpoints.

In [18]:
arr2 = np.linspace(5,35,7)
arr2

array([ 5., 10., 15., 20., 25., 30., 35.])

3. Create a 4 x 3 NumPy array filled with 9. Change the element in the third row and second column to 0.

In [19]:
arr3 = np.full((4,3),9)
arr3[2,1] =0
arr3

array([[9, 9, 9],
       [9, 9, 9],
       [9, 0, 9],
       [9, 9, 9]])

Q4. Calculate the remainder when each element is divided by 5.

In [20]:
a = np.array([6, 12, 18, 24])

print(a % 5)

[1 2 3 4]

Q5. Create an array and extract elements at indices 1, 3, and 5 using slicing.

In [21]:
arr = np.array([14, 28, 42, 56, 70, 84])

print(arr[1::2])

[28 56 84]

In [22]:
import numpy as np

arr = np.array([-16, 25, -36, 49])

absolute = np.abs(arr)
result = np.sqrt(absolute)

print("Absolute values:", absolute)
print("Square roots:", result)

Absolute values: [16 25 36 49]
Square roots: [4. 5. 6. 7.]

Create a 3 x 2 matrix containing numbers 7 to 12. Display its transpose and state its shape before and after transposition.

In [23]:
arr = np.arange(7, 13).reshape(3, 2)

print("Original Matrix:")
print(arr)
print("Shape before transpose:", arr.shape)

transposed = arr.T

print("\nTransposed Matrix:")
print(transposed)
print("Shape after transpose:", transposed.shape)

Original Matrix:
[[ 7  8]
 [ 9 10]
 [11 12]]
Shape before transpose: (3, 2)

Transposed Matrix:
[[ 7  9 11]
 [ 8 10 12]]
Shape after transpose: (2, 3)

 Calculate the range (maximum minus minimum) and median temperature. temperatures = np.array([18, 22, 27, 31, 24, 19])

In [24]:
temperatures = np.array([18, 22, 27, 31, 24, 19])

# Calculate range
temp_range = np.max(temperatures) - np.min(temperatures)

# Calculate median
median_temp = np.median(temperatures)

print("Temperature Range:", temp_range)
print("Median Temperature:", median_temp)

Temperature Range: 13
Median Temperature: 23.0

. Display distinct values in ascending order and determine how many distinct values are present. values = np.array([4, 9, 4, 2, 9, 7, 2, 4])

In [25]:
values = np.array([4, 9, 4, 2, 9, 7, 2, 4]) # Find disvatinct values in ascending order distinct = np.unique(values) # Count distinct values count = len(distinct) print("Distinct values:", distinct) print("Number of distinct values:", count)
values

array([4, 9, 4, 2, 9, 7, 2, 4])

 Use np.where() to create a new array containing Fast for speeds of at least 60 and Normal otherwise. speed = np.array([35, 62, 48, 81, 55])

In [26]:
a = np.array([35, 62, 48, 81, 55])

result = np.where(a >= 60, "Fast", "Normal")

print(result)

['Normal' 'Fast' 'Normal' 'Fast' 'Normal']

 Create a Pandas Series representing books issued on Monday, Tuesday, Wednesday, and Thursday, using [24, 31, 19, 27] and the corresponding day labels.

In [27]:
books = pd.Series( [24, 31, 19, 27], index=["Monday", "Tuesday", "Wednesday", "Thursday"] )
print(books)

Monday       24
Tuesday      31
Wednesday    19
Thursday     27
dtype: int64

 Create a Series with labels Laptop, Tablet, Phone and values [45000, 18000, 22000]. Retrieve the tablet price using its label.

In [28]:
a = pd.Series([45000, 18000, 22000], index=["Laptop", "Tablet", "Phone"])
print(a["Tablet"])

18000

 Display only rainfall measurements greater than 10. rainfall = pd.Series([12, 0, 18, 5, 23])

In [29]:
a = pd.Series([12, 0, 18, 5, 23])
print(a[a>10])

0    12
2    18
4    23
dtype: int64

4. Create a Series from the following dictionary. Display its index and values separately. {'Gold': 7200, 'Silver': 95, 'Copper': 850}

In [30]:
a = pd.Series({'Gold': 7200, 'Silver': 95, 'Copper': 850})
print(a.index)
print(a.values)

Index(['Gold', 'Silver', 'Copper'], dtype='object')
[7200   95  850]

Given a Series ratings containing [3.5, 4.2, 2.8, 4.7], assign Customer Ratings as its name and Review ID as its index name.

In [31]:
a = pd.Series([3.5, 4.2, 2.8, 4.7])
a.name = "Customer Ratings"
a.index.name = "Review ID"
print(a)

Review ID
0    3.5
1    4.2
2    2.8
3    4.7
Name: Customer Ratings, dtype: float64

Check whether X2 exists as an index label and whether X4 is absent. s = pd.Series([11, 22, 33], index=['X1', 'X2', 'X3'])

In [32]:
a = pd.Series([11, 22, 33], index=['X1', 'X2', 'X3'])
print(a.index.isin(['X2']))
print(a.index.isin(['X4']))

[False  True False]
[False False False]

 Convert the following Series into a dictionary and display the result. stock = pd.Series([16, 28, 12],                  index=['Keyboard', 'Mouse', 'Monitor'])

In [33]:
a = pd.Series([16, 28, 12], index=['Keyboard', 'Mouse', 'Monitor'])
print(a.to_dict())

{'Keyboard': 16, 'Mouse': 28, 'Monitor': 12}

 Create a Series from the dictionary below using index order Computer, Hindi, Art, English. Identify the missing entry. {'Hindi': 78, 'English': 84, 'Computer': 91}

In [34]:
b = pd.Series({'Hindi': 78, 'English': 84, 'Computer': 91}, index=['Computer', 'Hindi', 'Art', 'English'])
print(b)

Computer    91.0
Hindi       78.0
Art          NaN
English     84.0
dtype: float64

. Display the Boolean results of isnull() and notnull(). expenses = pd.Series([1200, None, 850, None, 600])

In [35]:
c = pd.Series([1200, None, 850, None, 600])
print(c.isnull())
print(c.notnull())

0    False
1     True
2    False
3     True
4    False
dtype: bool
0     True
1    False
2     True
3    False
4     True
dtype: bool

Predict the result of adding these Series, which have matching labels in different orders. a = pd.Series([8, 15, 22], index=['P', 'Q', 'R']) b = pd.Series([4, 6, 10], index=['R', 'P', 'Q']) print(a + b)

In [36]:
c = pd.Series([8, 15, 22], index=['P', 'Q', 'R'])
d = pd.Series([4, 6, 10], index=['R', 'P', 'Q'])
print(c + d)

P    14
Q    25
R    26
dtype: int64

A shop records daily sales for three products over four days. Calculate total sales for each day, total sales of each product, and identify the day with the highest combined sales. Rows represent Days 1-4. sales = np.array([    [120, 150, 180],    [140, 160, 175],    [135, 155, 190],    [150, 170, 200] ])

In [37]:
les = np.array([ [120, 150, 180], [140, 160, 175], [135, 155, 190], [150, 170, 200] ]) # Total sales for each day (row-wise) daily_sales = np.sum(sales, axis=1) # Total sales for each product (column-wise) product_sales = np.sum(sales, axis=0) # Day with the highest combined sales highest_day = np.argmax(daily_sales) + 1 print("Total sales for each day:", daily_sales) print("Total sales for each product:", product_sales) print("Day with highest combined sales: Day", highest_day) print("Highest combined sales:", np.max(daily_sales))
les

array([[120, 150, 180],
       [140, 160, 175],
       [135, 155, 190],
       [150, 170, 200]])

. Create a 6 x 6 array containing integers 10 to 45. Extract row indices 2 through 5 and column indices 1 through 4, inclusive, using zero-based indexing. Calculate the extracted submatrix mean.

In [38]:
arr = np.arange(10, 46).reshape(6, 6)

# Extract rows 2 through 5 and columns 1 through 4
submatrix = arr[1:5, 0:4]

 Use Boolean indexing to identify weights above 70. Use np.where() to replace weights below 55 with 55 in a new array without changing the original. weights = np.array([48, 62, 75, 81, 54, 69, 90])

In [39]:
a = np.array([48, 62, 75, 81, 54, 69, 90])
print(a[a>70])
print(np.where(a<55,55,a))

[75 81 90]
[55 62 75 81 55 69 90]

Calculate each product's total cost, the overall bill, and each product's percentage contribution to the bill. quantity = np.array([3, 5, 2, 7]) price = np.array([120, 80, 250, 60])

In [40]:
arr = np.array([3, 5, 2, 7])
arr2 = np.array([120, 80, 250, 60])
print(arr*arr2)

[360 400 500 420]

 Create a 3 x 4 array of your choice. Calculate variance and standard deviation separately for each row and column. Explain axis=0 and axis=1.

In [41]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(np.var(arr, axis=0))

[10.66666667 10.66666667 10.66666667 10.66666667]

 Choose a 2 x 3 matrix and a 3 x 2 matrix. Perform matrix multiplication. Explain why element-wise multiplication cannot be performed directly between their shapes.

In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10], [11, 12]])
print(np.dot(arr, arr2))

[[ 58  64]
 [139 154]]

Generate 25 random integers from 10 to 99, inclusive. Sort them, extract the five largest values, and determine the number of unique observations.

In [43]:
arr = np.random.randint(10, 100, 25)
print(np.sort(arr))
print(np.unique(arr))

[15 25 26 27 29 32 34 36 40 42 52 56 57 59 62 65 69 72 75 76 78 82 90 92
 94]
[15 25 26 27 29 32 34 36 40 42 52 56 57 59 62 65 69 72 75 76 78 82 90 92
 94]

Predict the final contents of a, b, and c. Explain the difference between a view and an independent copy. a = np.array([5, 10, 15, 20, 25, 30]) b = a[1:5] c = a[1:5].copy() b[1] = 99 c[2] = 77

In [44]:
arr = np.array([5, 10, 15, 20, 25, 30])
arr2 = arr[1:5]
arr3 = arr[1:5].copy()
arr2[1] = 99
arr3[2] = 77
print(arr)
print(arr2)
print(arr3)

[ 5 10 99 20 25 30]
[10 99 20 25]
[10 15 77 25]

Add the monthly-revenue Series, identify labels producing missing values, and explain index alignment. dept_a = pd.Series({'Jan': 250, 'Feb': 310, 'Mar': 290}) dept_b = pd.Series({'Mar': 180, 'Jan': 210, 'Apr': 260})

In [45]:
arr = pd.Series({'Jan': 250, 'Feb': 310, 'Mar': 290})
arr2 = pd.Series({'Mar': 180, 'Jan': 210, 'Apr': 260})

Identify students with attendance below 75%, display their labels, and count them. attendance = pd.Series(    [82, 67, 91, 74, 58],    index=['S101', 'S102', 'S103', 'S104', 'S105'] )

In [46]:
arr = pd.Series([82, 67, 91, 74, 58], index=['S101', 'S102', 'S103', 'S104', 'S105'])

Predict the Series output, identify the missing value, and explain why Pencil does not appear. inventory = {'Pen': 50, 'Pencil': 80,             'Eraser': 40, 'Scale': 25} labels = ['Scale', 'Pen', 'Marker', 'Eraser'] s = pd.Series(inventory, index=labels)

In [51]:
arr = {'Pen': 50, 'Pencil': 80, 'Eraser': 40, 'Scale': 25}
arr2 = ['Scale', 'Pen', 'Marker', 'Eraser']
arr3 = pd.Series(arr, index=arr2)
arr

{'Pen': 50, 'Pencil': 80, 'Eraser': 40, 'Scale': 25}

. Predict the result, identify non-missing entries using notnull(), and explain why subtraction is label-based rather than position-based. s1 = pd.Series([100, 200, 300],               index=['North', 'South', 'East']) s2 = pd.Series([10, 20, 30],               index=['South', 'West', 'North']) result = s1 - s2

In [53]:
arr = pd.Series([100, 200, 300], index=['North', 'South', 'East'])
arr2 = pd.Series([10, 20, 30], index=['South', 'West', 'North'])
arr3 = arr - arr2
arr3

East       NaN
North     70.0
South    190.0
West       NaN
dtype: float64

 Create a Series of electricity consumption for five households using meaningful labels. Filter consumption above 250 units, convert the filtered Series to a dictionary, and reconstruct a new Series.

In [54]:
# Create a Series for five households
consumption = pd.Series(
    [180, 320, 250, 400, 275],
    index=['House_A', 'House_B', 'House_C', 'House_D', 'House_E'],
    name='Electricity_Units'
)

print("Original Series:")
print(consumption)

# Filter consumption above 250 units
filtered = consumption[consumption > 250]
print("\nConsumption Above 250 Units:")
print(filtered)

# Convert the filtered Series into a dictionary
data_dict = filtered.to_dict()
print("\nDictionary:")
print(data_dict)

# Reconstruct a new Series from the dictionary
new_series = pd.Series(data_dict)
print("\nReconstructed Series:")
print(new_series)

Original Series:
House_A    180
House_B    320
House_C    250
House_D    400
House_E    275
Name: Electricity_Units, dtype: int64

Consumption Above 250 Units:
House_B    320
House_D    400
House_E    275
Name: Electricity_Units, dtype: int64

Dictionary:
{'House_B': 320, 'House_D': 400, 'House_E': 275}

Reconstructed Series:
House_B    320
House_D    400
House_E    275
dtype: int64

Predict s[s >= 50], identify missing entries using isnull(), and state the Series and index names. s = pd.Series({'A': 45, 'B': 70, 'C': 55},              index=['C', 'D', 'A', 'B']) s.name = 'Performance' s.index.name = 'Group'

In [56]:
s = pd.Series({'A': 45, 'B': 70, 'C': 55}, index=['C', 'D', 'A', 'B'])
s.name = 'Performance'
s.index.name = 'Group'
s[s>=50]

Group
C    55.0
B    70.0
Name: Performance, dtype: float64

. Predict s[s >= 50], identify missing entries using isnull(), and state the Series and index names. s = pd.Series({'A': 45, 'B': 70, 'C': 55},              index=['C', 'D', 'A', 'B']) s.name = 'Performance' s.index.name = 'Group'

In [58]:

s = pd.Series({'A': 45, 'B': 70, 'C': 55},
              index=['C', 'D', 'A', 'B'])

s.name = 'Performance'
s.index.name = 'Group'

# Filter values greater than or equal to 50
print("Filtered Series:")
print(s[s >= 50])

# Identify missing entries
print("\nMissing Entries:")
print(s.isnull())

# Display Series and index names
print("\nSeries Name:", s.name)
print("Index Name:", s.index.name)

Filtered Series:
Group
C    55.0
B    70.0
Name: Performance, dtype: float64

Missing Entries:
Group
C    False
D     True
A    False
B    False
Name: Performance, dtype: bool

Series Name: Performance
Index Name: Group

 Examination performance analysis: Generate a reproducible 12 x 4 NumPy array of integer test marks from 20 to 100, inclusive, using a fixed seed. Calculate each student's average and each test's mean and standard deviation. Count students passing all four tests (at least 40 in each). Identify students with averages of at least 75 and the test with greatest variation. State your student numbering convention

In [59]:
arr = np.random.randint(20, 101, size=(12, 4))
print(arr)

[[ 43  40  25  51]
 [ 54  54  41  80]
 [ 39  72  65  91]
 [ 90  31  94  36]
 [ 97  43  95  50]
 [ 31  58  32  31]
 [ 77  50  37  70]
 [ 34  55  69  84]
 [ 83 100  31  86]
 [ 63  59  32  93]
 [ 65  25  69  47]
 [ 52  43  44  43]]

In [61]:
# Generate reproducible marks (12 students, 4 tests)
np.random.seed(42)
marks = np.random.randint(20, 101, size=(12, 4))

print("Marks of 12 Students:")
print(marks)

# Calculate each student's average (row-wise)
student_avg = np.mean(marks, axis=1)
print("\nAverage Marks of Each Student:")
print(np.round(student_avg, 2))

# Calculate each test's mean (column-wise)
test_mean = np.mean(marks, axis=0)
print("\nMean of Each Test:")
print(np.round(test_mean, 2))

# Calculate each test's standard deviation
test_std = np.std(marks, axis=0)
print("\nStandard Deviation of Each Test:")
print(np.round(test_std, 2))

# Count students passing all four tests (at least 40 in each)
pass_all = np.all(marks >= 40, axis=1)
print("\nNumber of Students Passing All Four Tests:")
print(np.sum(pass_all))

# Identify students with averages >= 75
high_performers = np.where(student_avg >= 75)[0] + 1
print("\nStudents with Average >= 75 (Student Numbers):")
print(high_performers)

# Identify the test with greatest variation
most_variable_test = np.argmax(test_std) + 1
print("\nTest with Greatest Variation:")
print("Test", most_variable_test)

Marks of 12 Students:
[[71 34 91 80]
 [40 94 94 43]
 [22 41 72 21]
 [49 57 21 83]
 [79 40 52 95]
 [77 41 68 78]
 [61 79 99 34]
 [81 81 66 81]
 [70 74 83 22]
 [70 26 40 92]
 [58 37 23 79]
 [33 28 72 21]]

Average Marks of Each Student:
[69.   67.75 39.   52.5  66.5  66.   68.25 77.25 62.25 57.   49.25 38.5 ]

Mean of Each Test:
[59.25 52.67 65.08 60.75]

Standard Deviation of Each Test:
[18.49 22.41 25.16 28.5 ]

Number of Students Passing All Four Tests:
4

Students with Average >= 75 (Student Numbers):
[8]

Test with Greatest Variation:
Test 4

 Matrix transformation and analysis: Construct a 5 x 5 matrix containing integers 21 to 45. Extract the central 3 x 3 matrix, transpose it, and calculate the matrix product of the extracted matrix with its transpose. Calculate row-wise sums of the product and identify its maximum and all positions tied at that maximum. Explain dimensions at every stage.

In [63]:
# Step 1: Create a 5 x 5 matrix containing integers 21 to 45
A = np.arange(21, 46).reshape(5, 5)
print("Original Matrix (5 x 5):")
print(A)

# Step 2: Extract the central 3 x 3 matrix
B = A[1:4, 1:4]
print("\nCentral Matrix (3 x 3):")
print(B)

# Step 3: Transpose the extracted matrix
BT = B.T
print("\nTranspose of Central Matrix (3 x 3):")
print(BT)

# Step 4: Calculate matrix product
C = B @ BT
print("\nMatrix Product (3 x 3):")
print(C)

# Step 5: Calculate row-wise sums
row_sums = np.sum(C, axis=1)
print("\nRow-wise Sums:")
print(row_sums)

# Step 6: Find maximum row sum
maximum = np.max(row_sums)
print("\nMaximum Row Sum:")
print(maximum)

# Step 7: Find all positions tied at the maximum
positions = np.where(row_sums == maximum)[0]
print("\nPositions of Maximum Row Sum (0-based):")
print(positions)

print("\nPositions of Maximum Row Sum (1-based):")
print(positions + 1)

Original Matrix (5 x 5):
[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]]

Central Matrix (3 x 3):
[[27 28 29]
 [32 33 34]
 [37 38 39]]

Transpose of Central Matrix (3 x 3):
[[27 32 37]
 [28 33 38]
 [29 34 39]]

Matrix Product (3 x 3):
[[2354 2774 3194]
 [2774 3269 3764]
 [3194 3764 4334]]

Row-wise Sums:
[ 8322  9807 11292]

Maximum Row Sum:
11292

Positions of Maximum Row Sum (0-based):
[2]

Positions of Maximum Row Sum (1-based):
[3]

 Sales and revenue analysis: Create a 6 x 4 matrix of quantities sold over six days for four products. Use unit prices [150, 240, 90, 320]. Calculate daily revenue, total revenue per product, the highest-revenue day, and the best-selling product by quantity. Reduce prices by 10% for products whose total quantity exceeds 100, then recalculate total revenue without modifying original prices.

In [ ]:
sales = np.array([
    [20, 15, 30, 10],
    [25, 20, 25, 15],
    [18, 25, 20, 12],
    [30, 18, 35, 20],
    [22, 30, 28, 18],
    [28, 22, 32, 25]
])


prices = np.array([150, 240, 90, 320])


print(sales)
print(prices)


daily_revenue = np.sum(sales * prices, axis=1)
print("\nDaily Revenue:")
print(daily_revenue)


product_revenue = np.sum(sales * prices, axis=0)
print("\nTotal Revenue per Product:")
print(product_revenue)


highest_day = np.argmax(daily_revenue) + 1
print("\nHighest Revenue Day:")
print("Day", highest_day)


product_quantity = np.sum(sales, axis=0)
best_product = np.argmax(product_quantity) + 1

print("\nTotal Quantity Sold per Product:")
print(product_quantity)

print("\nBest-Selling Product:")
print("Product", best_product)

# Step 6: Reduce prices by 10% for products with total quantity > 100
discounted_prices = np.where(
    product_quantity > 100,
    prices * 0.90,
    prices
)

print("\nDiscounted Unit Prices:")
print(discounted_prices)


discounted_revenue = np.sum(sales * discounted_prices)
print(np.sum(product_revenue))
print(discounted_revenue)
print(prices)

 Random data cleaning and statistics: Generate 100 normal observations with mean 50 and standard deviation 12 using a fixed seed. Count values outside 30-70 and replace them with the nearest boundary using np.where(). Compare original and cleaned mean, variance, standard deviation, minimum, and maximum. Explain the statistical effects of boundary replacement.

In [65]:
np.random.seed(42)
data = np.random.normal(50, 12, 100)

# Count values outside 30–70
count = np.sum((data < 30) | (data > 70))

# Replace out-of-range values with nearest boundary
cleaned = np.where(data < 30, 30, np.where(data > 70, 70, data))

print("Values outside range:", count)

print("\nOriginal Data:")
print("Mean:", np.mean(data))
print("Variance:", np.var(data))
print("Standard Deviation:", np.std(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))

print("\nCleaned Data:")
print("Mean:", np.mean(cleaned))
print("Variance:", np.var(cleaned))
print("Standard Deviation:", np.std(cleaned))
print("Minimum:", np.min(cleaned))

Values outside range: 7

Original Data:
Mean: 48.75384179127088
Variance: 117.57919603591557
Standard Deviation: 10.843394119735553
Minimum: 18.56305875092307
Maximum: 72.22733821410725

Cleaned Data:
Mean: 48.967755094142284
Variance: 105.99277431898325
Standard Deviation: 10.295279224915818
Minimum: 30.0

Multi-branch financial reconciliation: Combine the three earnings Series by ordinary addition. Explain missing values, identify quarters common to all branches, and calculate their combined earnings. Construct a separate result treating absent branch records as zero and explain how its interpretation differs. branch_a = pd.Series({'Q1': 120, 'Q2': 145, 'Q4': 180}) branch_b = pd.Series({'Q2': 110, 'Q3': 135, 'Q4': 155}) branch_c = pd.Series({'Q1': 95, 'Q3': 125, 'Q4': 140})

In [67]:
branch_a = pd.Series({'Q1': 120, 'Q2': 145, 'Q4': 180})
branch_b = pd.Series({'Q2': 110, 'Q3': 135, 'Q4': 155})
branch_c = pd.Series({'Q1': 95, 'Q3': 125, 'Q4': 140})

# Ordinary addition
combined = branch_a + branch_b + branch_c

print(combined)

# Quarters common to all branches
common = branch_a.index.intersection(branch_b.index).intersection(branch_c.index)

print(common)


print(combined.loc[common])

# Treat missing branch records as zero
combined_zero = branch_a.add(branch_b, fill_value=0).add(branch_c, fill_value=0)

print(combined_zero)

Q1      NaN
Q2      NaN
Q3      NaN
Q4    475.0
dtype: float64
Index(['Q4'], dtype='object')
Q4    475.0
dtype: float64
Q1    215.0
Q2    255.0
Q3    260.0
Q4    475.0
dtype: float64

. Series data integrity: Preserve the required index order, identify missing student records, and filter valid scores of at least 70. Convert the filtered Series to a dictionary, reconstruct it as a Series, and verify that labelled values match. Explain why missing records should not automatically be zero marks. scores = {'R101': 78, 'R102': 65, 'R104': 92, 'R105': 48} required = ['R105', 'R103', 'R101', 'R106', 'R104', 'R102'] s = pd.Series(scores, index=required)

In [68]:

scores = {'R101': 78, 'R102': 65, 'R104': 92, 'R105': 48}
required = ['R105', 'R103', 'R101', 'R106', 'R104', 'R102']

s = pd.Series(scores, index=required)
print(s)
print(s[s.isnull()])

filtered = s[s >= 70]
print(filtered)

data_dict = filtered.to_dict()
print(data_dict)
new_s = pd.Series(data_dict)
print(new_s)
print("\nValues Match:", filtered.equals(new_s))

R105    48.0
R103     NaN
R101    78.0
R106     NaN
R104    92.0
R102    65.0
dtype: float64
R103   NaN
R106   NaN
dtype: float64
R101    78.0
R104    92.0
dtype: float64
{'R101': 78.0, 'R104': 92.0}
R101    78.0
R104    92.0
dtype: float64

Values Match: True